### ISSUE TITLE
[3pt,0pt] Review, improve and formalize the URI protocol

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/opencmw-cpp#194]

**Comment by RalphSteinhagen** [comment]
see also: [Fix and docment mapping between Rest Backend URIs and majordomo service name and topic#214](https://github.com/fair-acc/opencmw-cpp/issues/214) (possible duplicate)

**Comment by ivan-cukic** [comment]
URI mapping was fixed in https://github.com/fair-acc/opencmw-cpp/pull/260, #317 adds the documentation explaining the mapping.
