### ISSUE TITLE
[3pt/8pt] Integrate GNU Radio sinks with the OpenCMW Disruptor

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/opencmw-cpp#197]

**Comment by RalphSteinhagen** [comment]
... will be contributed directly to GNU Radio dev-4.0 branch.

**Comment by frankosterfeld** [comment]
Pull request at https://github.com/fair-acc/graph-prototype/pull/80 (with very generic interface for multiplexing, timingctx implementation should probably go to gr-digitizer?)
