### ISSUE TITLE
[3pt,0pt] Evaluate approaches for GR4-flowgraph integration with the OpenCMW Disruptor

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/opencmw-cpp#199]

**Comment by RalphSteinhagen** [comment]
The original idea of splitting the sample-by-sample streaming and chunked data processing (using 'DataSet' objects) between GNU Radio and OpenCMW was dropped in favour of doing both types of processing in GNU Radio.

This design decision has been discussed and agreed upon during the GNU Radio 4.0 Architecture meeting. See ([expanded](https://github.com/fair-acc/opencmw-cpp/files/11507835/20230316_GNU_Radio_DataSet_API-expanded.pdf)) [slides](https://github.com/fair-acc/opencmw-cpp/files/11507836/20230316_GNU_Radio_DataSet_API.pdf) for details.

Thanks to the new `circular_buffer<T>` implementation the updated concepts can pass `DataSet<T>'-type objects directly between blocks. Tentatively, the following type definition has been agreed upon:
![image](https://github.com/fair-acc/opencmw-cpp/assets/46007894/64fba92d-2aac-434a-82c4-ea50edba81f9)

This streamlines both the processing, graph-based definition, and editing into one common framework, reducing the need for the Disruptor pattern and obsoletes the need for RxCpp in the original proposal entirely.

![image](https://github.com/fair-acc/opencmw-cpp/assets/46007894/fd91537b-64fb-49a4-81da-363c2101df8c)

See the slides linked above for details.

This also closes https://github.com/fair-acc/opencmw-cpp/issues/200.
