### ISSUE TITLE
[5pt] Implement gr4-flowgraph integration with the OpenCMW Disruptor

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/opencmw-cpp#200]

**Comment by RalphSteinhagen** [comment]
The original idea of splitting the sample-by-sample streaming and chunked data processing (using 'DataSet' objects) between GNU Radio and OpenCMW was dropped in favour of doing both types of processing in GNU Radio.

This design decision has been discussed and agreed upon during the GNU Radio 4.0 Architecture meeting. See ([expanded](https://github.com/fair-acc/opencmw-cpp/files/11507835/20230316_GNU_Radio_DataSet_API-expanded.pdf)) [slides](https://github.com/fair-acc/opencmw-cpp/files/11507836/20230316_GNU_Radio_DataSet_API.pdf) for details.

See also https://github.com/fair-acc/opencmw-cpp/issues/199.
