### ISSUE TITLE
[0pt] Optimize REST backend to work with several clients

### ISSUE THREAD

**Issue by ivan-cukic** [fair-acc/opencmw-cpp#231]
1. Keep subscriptions open for a specified number of seconds after the REST client goes away to remove reconnecting if a new client pops up that wants the same service (or if the same client sends a new request)
2. Allow having a single client that requests several services
3. Add 'persistent' URLs for caching clients

**Comment by RalphSteinhagen** [comment]
## some additional information:
one of the OpenCMW goals is that recurring/similar REST user requests can be cached by transparent HTTP proxies (external to OpenCMW, e.g. [Squid](http://www.squid-cache.org/)) to optimise the actual required bandwidth/cpu usage on the service, to efficiently fan-out the same information to multiple clients (e.g. fixed-display applications/dashboards), and is also essential to be able to safely forward/route 'GET' requests to unsafe/public networks.

The issue/need for the modification is that most caching HTTP proxies by-default only cache 'GET' responses and primarily rely on the URI and MIME-type as the cache key. For further details see, for example, [RFC 9111](https://httpwg.org/specs/rfc9111.html#rfc.section.2.p.3):
> [..] However, many HTTP caches in common use today only cache GET responses and therefore only use the URI as the cache key.

and Mozilla's [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#cache_busting) on cache busting:
> [..] And for resources that do change, it is a common best practice to change the URL each time the content changes, so that the URL unit can be cached for a longer period.

### query parameter implementation detail
Thus, in complementary to using [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), the 'RestBackend' would need to be modified to support long-polling using an additional query parameter (proposal: `LongPollingIdx`) with a  unique counter for each notification/subscription e.g.
`http://.../path?signals=A,B,C&LongPollingIdx=0`,
`http://.../path?signals=A,B,C&LongPollingIdx=1`,
`http://.../path?signals=A,B,C&LongPollingIdx=2`,
...
`http://.../path?signals=A,B,C&LongPollingIdx=7`,
`http://.../path?signals=A,B,C&LongPollingIdx=8`
In this scheme, every client polling for, for example, `http://.../path?signals=A,B,C&LongPollingIdx=8`, would receive the same message/data either by the external HTTP proxy and/or browser cache. The additional `LongPollingIdx` should be shielded from the OpenCMW worker functions (ie. added/removed by the RestBackend as needed).

### [TLRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#Time_aware_least_recently_used_(TLRU))-based caching
The caching functionality extends the common long-polling scheme and allows clients that may have lost a couple of updates to catch up and retrieve the last (usually only a few) updates. Here, the server would return, for example, serve the data for `http://.../path?signals=A,B,C&LongPollingIdx=2` and redirect (N.B. via HTTP return code '302') the client to the newer available URI `http://.../path?signals=A,B,C&LongPollingIdx=3` until the last notified index has been reached (i.e. `LongPollingIdx=8`), forward a new URI with `LongPollingIdx=9` which would cause the client GET to block until the base-URI is notified with new data. In this scheme, invalid `LongPollingIdx` would either be mapped to the latest (i.e. '8' ) or redirected to the next to be emitted index (i.e. '9'). 

### Other consideration
While modifying the RestBackend it may be useful also to consolidate the use of URIs as outlined in #194 and #214.
